# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
#from urllib.request import urlretrieve

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
#url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
# urlretrieve(url, 'chipotle.tsv')
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', delimiter ='\t')
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [3]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

### Step 4. How many products cost more than $10.00?

In [4]:
chipo.item_price = chipo.item_price.apply(lambda price: float(price.split("$")[1]))

price_over10_count = chipo[chipo.item_price > 10.00].item_price.count()
price_over10_count

1130

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [5]:
name_price = chipo[["item_name","item_price"]]
name_price.head()

                               item_name  item_price
0           Chips and Fresh Tomato Salsa        2.39
1                                   Izze        3.39
2                       Nantucket Nectar        3.39
3  Chips and Tomatillo-Green Chili Salsa        2.39
4                           Chicken Bowl       16.98

### Step 6. Sort by the name of the item

In [6]:
chipo = chipo.sort_values(['item_name'], ascending=True)
chipo.head(100)

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
3422,1373,1,6 Pack Soft Drink,[Coke],6.49
553,230,1,6 Pack Soft Drink,[Diet Coke],6.49
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49
1922,776,1,6 Pack Soft Drink,[Coke],6.49
1937,784,1,6 Pack Soft Drink,[Diet Coke],6.49
3836,1537,1,6 Pack Soft Drink,[Coke],6.49
298,129,1,6 Pack Soft Drink,[Sprite],6.49
1976,798,1,6 Pack Soft Drink,[Diet Coke],6.49
1167,481,1,6 Pack Soft Drink,[Coke],6.49
3875,1554,1,6 Pack Soft Drink,[Diet Coke],6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49
3886,1558,1,6 Pack Soft Drink,[Diet Coke],6.49
2108,849,1,6 Pack Soft Drink,[Coke],6.49
3010,1196,1,6 Pack Soft Drink,[Diet Coke],6.49
4535,1803,1,6 Pack Soft Drink,[Lemonade],6.49
4169,1664,1,6 Pack Soft Drink,[Diet Coke],6.49
4174,1666,1,6 Pack Soft Drink,[Coke],6.49
4527,1800,1,6 Pack Soft Drink,[Diet Coke],6.49
4522,1798,1,6 Pack Soft Drink,[Diet Coke],6.49
3806,1525,1,6 Pack Soft Drink,[Sprite],6.49
2389,949,1,6 Pack Soft Drink,[Coke],6.49
3132,1248,1,6 Pack Soft Drink,[Diet Coke],6.49
3141,1253,1,6 Pack Soft Drink,[Lemonade],6.49
639,264,1,6 Pack Soft Drink,[Diet Coke],6.49
1026,422,1,6 Pack Soft Drink,[Sprite],6.49
...,...,...,...,...,...
471,202,1,Barbacoa Bowl,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",11.48
115,51,1,Barbacoa Bowl,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",8.99
1417,576,1,Barbacoa Bowl,[Tomatillo Red Chili Salsa],9.25
1264,514,1,Barbacoa Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",9.25
1068,440,1,Barbacoa Bowl,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Let...",9.25
1804,730,1,Barbacoa Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",8.99
4380,1748,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.75
1236,504,1,Barbacoa Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",11.48
1235,504,1,Barbacoa Bowl,"[Tomatillo-Green Chili Salsa (Medium), [Black ...",11.48
3822,1533,1,Barbacoa Bowl,"[Fresh Tomato (Mild), [Lettuce, Rice, Cheese]]",8.69
1670,676,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.25
3394,1361,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.75
2517,1000,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",9.25
1347,550,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.25
3547,1426,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",11.75
3376,1356,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",9.25
1970,795,1,Barbacoa Bowl,[Tomatillo Red Chili Salsa],9.25
1179,485,1,Barbacoa Bowl,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",8.99
1175,483,1,Barbacoa Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",11.48
1174,483,1,Barbacoa Bowl,"[Tomatillo-Green Chili Salsa (Medium), [Black ...",11.48
1650,667,1,Barbacoa Bowl,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",8.99
2013,812,1,Barbacoa Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",11.75
4441,1770,1,Barbacoa Bowl,"[Tomatillo Green Chili Salsa, [Rice, Cheese, G...",11.75
2073,836,1,Barbacoa Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",11.75
254,110,1,Barbacoa Bowl,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Let...",9.25
3549,1426,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.25
1643,664,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.75
1357,554,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25
592,244,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Rice, Cheese, Lett...",9.25
3245,1299,1,Barbacoa Bowl,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",8.99

### Step 7. What was the quantity of the most expensive item ordered?

In [7]:
expensive_item = chipo.item_price.max()
expensive_item

44.25

In [8]:
quantity_exp = chipo[chipo.item_price==expensive_item]['quantity']
quantity_exp

3598    15
Name: quantity, dtype: int64

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [9]:
count_veggie_salad = chipo[chipo['item_name'].str.contains('Veggie Salad Bowl')==True].count().quantity
count_veggie_salad

18

### Step 9. How many times people orderd more than one Canned Soda?

In [10]:
count_soda_over1=chipo[chipo['item_name'].str.contains("Canned Soda")==True]
count_soda_over1[count_soda_over1['quantity']>1].count().quantity

20